version: "3.8"

services:
  boot-agent:
    image: ghcr.io/mrgarbonzo/boot-agent:main-90a238f
    container_name: panthers-boot-agent
    restart: "no"
    env_file: .env
    volumes:
      - sealed-output:/mnt/secure/boot-config

volumes:
  sealed-output:
